// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypouwhelcyzyhjrcldfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwb3V3aGVsY3l6eWhqcmNsZGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODc3NDIsImV4cCI6MjA3MzI2Mzc0Mn0.L6gF8wD5aufj3iACmGwXwAArxt5hcYmPjd-NZYlaofs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});